Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-09, with the labels that each got.

#520 feat: 운영 서버 배포 과정에 테스트 서버의 데이터베이스를 동기화하는 스크립트 추가 완료
  jenkins/prod/Jenkinsfile
  jenkins/prod/config.yml
Labels: ✨ Feature

#523 fix: 운영서버와 테스트 서버 DB 동기화 과정에서 SSH 인증 오류 수정 완료
  jenkins/prod/Jenkinsfile
Labels: 🐞 Bug

#525 fix: 삭제된 게시글로 인해 나의 댓글이 조회되지 않는 문제 수정
  src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardPersistenceAdapter.java
  src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardRepository.java
  src/main/java/page/clab/api/domain/community/board/application/port/out/RetrieveBoardPort.java
  src/main/java/page/clab/api/external/community/board/application/service/ExternalBoardRetrievalService.java
Labels: 🐞 Bug

#528 refactor: 화이트리스트 관리 방식 JSON → YAML 전환 및 서브넷 마스크 지원 기능 추가 완료
  .gitignore
  src/main/java/page/clab/api/global/auth/application/WhitelistService.java
  src/main/java/page/clab/api/global/auth/filter/CustomBasicAuthenticationFilter.java
  src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/page/clab/api/global/auth/util/IpWhitelistValidator.java
  src/main/java/page/clab/api/global/auth/util/WhitelistFileLoader.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/config/YamlConfig.java
  src/main/java/page/clab/api/global/util/IpAddressUtil.java
  src/main/java/page/clab/api/global/util/WhitelistPathMatcher.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#534 refactor: 활동 관련 2차 QA에 따른 활동 멤버 관련 로직 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/GroupMemberStatus.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/SingleLeaderModificationException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#536 refactor: 사용자 계정 생성 이메일 전송 로직 개선 및 이메일 재전송 API 추가 완료
  build.gradle
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberPasswordController.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/ResetMemberPasswordRequestController.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/ResetMemberPasswordVerificationController.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/event/ApplicationMemberCreatedProcessor.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/ManageMemberPasswordUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/RequestResetMemberPasswordUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/VerifyResetMemberPasswordUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberPasswordManagementService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRegisterService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/ResetMemberPasswordRequestService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/ResetMemberPasswordVerificationService.java
Labels: 🔨 Refactor

#538 refactor: 활동관련 2차 QA에 따른 활동 게시판 로직 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroup.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/ContentLengthExceededException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/resources/messages.properties
Labels: 🔨 Refactor

#541 refactor : 지원 알림에 모집 종류 명시하도록 수정
  src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationApplyService.java
  src/main/java/page/clab/api/domain/hiring/application/domain/Application.java
Labels: 🔨 Refactor

#539 refactor: 활동 관련 2차 QA에 따른 활동 관리 로직 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustom.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustomImpl.java
  src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
Labels: 🔨 Refactor

#547 refactor: 지원한 활동 목록에 본인이 생성한 활동이 나타나지 않도록 변경 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
Labels: 🔨 Refactor

#550 refactor: 활동 그룹 커리큘럼 글자 수 조정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroup.java
  src/main/resources/messages.properties
Labels: 🔨 Refactor

#551 refactor: 활동 그룹 목록을 가장 최신에 생성된 순으로 정렬되도록 변경 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupRepositoryCustomImpl.java
Labels: 🔨 Refactor

#553 refactor: 활동 상세 조회 응답에서 실제 참여인원만 반환하도록 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupDetailsRepositoryImpl.java
Labels: 🔨 Refactor

#565 refactor: 활동 3차 QA에 따른 활동 그룹 관련 기능 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
Labels: 🔨 Refactor

#566 refactor: 3차 QA에 따른 활동 게시판 관련 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoard.java
  src/main/resources/messages.properties
Labels: 🔨 Refactor

#567 refactor: 3차 QA에 따른 활동 관련 알림 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
Labels: 🔨 Refactor

#571 refactor: 이달의 생일자 조회 API 정렬 로직 개선 완료
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java
Labels: 🔨 Refactor
