Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-04, with the labels that each got.

#305 Setup Github Actions Gradle CI Build
  .github/workflows/spring-boot-gradle-ci.yml
  README.md
Labels: ⚙️ Setup

#308 fix(gradle): } 누락 수정
  build.gradle
Labels: 🐞 Bug

#309 GeoIP2 -> IPInfo 서비스 변경
  src/main/java/page/clab/api/domain/book/dao/BookLoanRecordRepositoryImpl.java
  src/main/java/page/clab/api/domain/book/dto/response/BookLoanRecordResponseDto.java
  src/main/java/page/clab/api/domain/login/application/LoginAttemptLogService.java
  src/main/java/page/clab/api/domain/login/domain/LoginAttemptLog.java
  src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
  src/main/java/page/clab/api/global/common/dto/IPInfoResponse.java
  src/main/java/page/clab/api/global/config/IPInfoConfig.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/config/WebConfig.java
  src/main/java/page/clab/api/global/util/HttpReqResUtil.java
  src/main/java/page/clab/api/global/util/IPInfoUtil.java
Labels: 🔨 Refactor
