Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-12, with the labels that each got.

#610 feat: 인기 게시글 기능 구현 완료
  src/main/java/page/clab/api/domain/community/board/adapter/in/web/HotBoardsRetrievalController.java
  src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardPersistenceAdapter.java
  src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/BoardRepository.java
  src/main/java/page/clab/api/domain/community/board/adapter/out/persistence/RedisHotBoardPersistenceAdapter.java
  src/main/java/page/clab/api/domain/community/board/application/port/in/RetrieveHotBoardsUseCase.java
  src/main/java/page/clab/api/domain/community/board/application/port/out/RegisterHotBoardPort.java
  src/main/java/page/clab/api/domain/community/board/application/port/out/RemoveHotBoardPort.java
  src/main/java/page/clab/api/domain/community/board/application/port/out/RetrieveBoardPort.java
  src/main/java/page/clab/api/domain/community/board/application/port/out/RetrieveHotBoardPort.java
  src/main/java/page/clab/api/domain/community/board/application/service/DefaultHotBoardSelectionStrategy.java
  src/main/java/page/clab/api/domain/community/board/application/service/HotBoardRegisterService.java
  src/main/java/page/clab/api/domain/community/board/application/service/HotBoardRetrievalService.java
  src/main/java/page/clab/api/domain/community/board/application/service/HotBoardSelectionStrategies.java
  src/main/java/page/clab/api/domain/community/board/application/service/HotBoardSelectionStrategy.java
Labels: ✨ Feature

#632 refactor: Jenkins Config YAML 기반 알림 플랫폼 유동적 지원 추가 완료
  jenkins/prod/Jenkinsfile
  jenkins/prod/config.yml
  jenkins/stage/Jenkinsfile
  jenkins/stage/config.yml
Labels: 🔨 Refactor, 🌎 Intra

#637 refactor: Jenkins Config YAML 기반 알림 플랫폼 유동적 지원 추가 완료
  jenkins/prod/Jenkinsfile
  jenkins/prod/config.yml
  jenkins/stage/Jenkinsfile
  jenkins/stage/config.yml
Labels: 🔨 Refactor, 🌎 Intra

#635 refactor : 게시글 이모지와 댓글 좋아요 누르기/취소하기 API 응답 DTO 반환하도록 수정
  src/main/java/page/clab/api/domain/community/board/adapter/in/web/BoardEmojiToggleController.java
  src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardDtoMapper.java
  src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardEmojiDtoMapper.java
  src/main/java/page/clab/api/domain/community/board/application/dto/response/BoardEmojiToggleResponseDto.java
  src/main/java/page/clab/api/domain/community/board/application/port/in/ToggleBoardEmojiUseCase.java
  src/main/java/page/clab/api/domain/community/board/application/service/BoardEmojiToggleService.java
  src/main/java/page/clab/api/domain/community/comment/adapter/in/web/CommentLikeToggleController.java
  src/main/java/page/clab/api/domain/community/comment/application/dto/mapper/CommentLikeDtoMapper.java
  src/main/java/page/clab/api/domain/community/comment/application/dto/response/CommentLikeToggleResponseDto.java
  src/main/java/page/clab/api/domain/community/comment/application/port/in/ToggleCommentLikeUseCase.java
  src/main/java/page/clab/api/domain/community/comment/application/service/CommentLikeToggleService.java
Labels: 🔨 Refactor

#639 refactor : 게시글 이모지 누르기/취소하기 api 응답에서 board category 추가
  src/main/java/page/clab/api/domain/community/board/application/dto/mapper/BoardEmojiDtoMapper.java
  src/main/java/page/clab/api/domain/community/board/application/dto/response/BoardEmojiToggleResponseDto.java
  src/main/java/page/clab/api/domain/community/board/application/service/BoardEmojiToggleService.java
  src/main/java/page/clab/api/domain/community/board/domain/BoardCategory.java
Labels: 🔨 Refactor

#641 refactor : BoardCategory의 key 표현 방식 소문자 + 스네이크로 롤백
  src/main/java/page/clab/api/domain/community/board/domain/BoardCategory.java
Labels: 🔨 Refactor
