Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-05, with the labels that each got.

#316 서버 인프라 설정 마이그레이션 완료
  .gitignore
  Dockerfile
  config/default
  config/nginx.conf
  docker-compose.yml
Labels: 🌎 Intra

#318 슬랙 메시지 개선 완료
  build.gradle
  src/main/java/page/clab/api/domain/application/api/ApplicationController.java
  src/main/java/page/clab/api/domain/application/application/ApplicationService.java
  src/main/java/page/clab/api/domain/login/application/LoginService.java
  src/main/java/page/clab/api/global/auth/filter/InvalidEndpointAccessFilter.java
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
  src/main/java/page/clab/api/global/config/SlackConfig.java
Labels: 🔨 Refactor

#322 기술 블로그 하이퍼링크 기능 추가 완료
  src/main/java/page/clab/api/domain/blog/domain/Blog.java
  src/main/java/page/clab/api/domain/blog/dto/request/BlogRequestDto.java
  src/main/java/page/clab/api/domain/blog/dto/request/BlogUpdateRequestDto.java
  src/main/java/page/clab/api/domain/blog/dto/response/BlogDetailsResponseDto.java
  src/main/java/page/clab/api/domain/blog/dto/response/BlogResponseDto.java
Labels: ✨ Feature

#328 도서 반환 및 대출 연장 오류 수정 완료
  src/main/java/page/clab/api/domain/book/application/BookLoanRecordService.java
  src/main/java/page/clab/api/domain/book/application/BookService.java
  src/main/java/page/clab/api/domain/book/dao/BookLoanRecordRepository.java
Labels: 🐞 Bug

#320 chore(github): update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Setup

#329 슬랙 에러 메시지 전송 오류 수정 완료
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🐞 Bug

#331 일부 에러 코드에 대한 응답 변경 완료
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#333 내 댓글 조회시 발생하는 오류 수정 완료
  src/main/java/page/clab/api/domain/comment/application/CommentService.java
  src/main/java/page/clab/api/domain/comment/dto/response/CommentMyResponseDto.java
Labels: 🐞 Bug

#335 게시글 및 댓글 반환 정보 수정 완료
  src/main/java/page/clab/api/domain/board/api/BoardController.java
  src/main/java/page/clab/api/domain/board/application/BoardService.java
  src/main/java/page/clab/api/domain/comment/application/CommentService.java
  src/main/java/page/clab/api/domain/comment/dto/response/CommentResponseDto.java
Labels: 🔨 Refactor

#337 favicon.ico 차단 문제 수정
  src/main/java/page/clab/api/global/config/SecurityConstants.java
Labels: 🐞 Bug

#339 공지사항 게시글에 대한 응답 변경 완료
  src/main/java/page/clab/api/domain/board/dto/response/BoardCategoryResponseDto.java
  src/main/java/page/clab/api/domain/board/dto/response/BoardDetailsResponseDto.java
  src/main/java/page/clab/api/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/page/clab/api/domain/board/dto/response/WriterInfo.java
Labels: 🔨 Refactor

#341 멤버 생성 및 이메일 템플릿 리팩토링 완료
  src/main/java/page/clab/api/domain/member/application/MemberService.java
  src/main/java/page/clab/api/domain/member/dao/MemberRepository.java
  src/main/java/page/clab/api/domain/member/exception/AssociatedAccountExistsException.java
  src/main/java/page/clab/api/domain/member/exception/DuplicateMemberContactException.java
  src/main/java/page/clab/api/domain/member/exception/DuplicateMemberEmailException.java
  src/main/java/page/clab/api/domain/member/exception/DuplicateMemberIdException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/resources/templates/clabEmail.html
Labels: 🔨 Refactor

#343 사용자 2단계 인증 정책 변경 완료
  src/main/java/page/clab/api/domain/login/api/LoginController.java
  src/main/java/page/clab/api/domain/login/application/LoginService.java
  src/main/java/page/clab/api/domain/login/dto/response/LoginHeader.java
  src/main/java/page/clab/api/domain/login/dto/response/LoginResult.java
  src/main/java/page/clab/api/domain/login/dto/response/TokenHeader.java
  src/main/java/page/clab/api/domain/member/domain/Member.java
  src/main/java/page/clab/api/domain/member/dto/request/MemberRequestDto.java
  src/main/java/page/clab/api/domain/member/dto/request/MemberUpdateRequestDto.java
  src/main/java/page/clab/api/domain/member/dto/response/MemberResponseDto.java
  src/main/java/page/clab/api/domain/member/dto/response/MyProfileResponseDto.java
  src/main/java/page/clab/api/global/auth/domain/ClabAuthResponseStatus.java
Labels: 🔨 Refactor, ✨ Feature

#345 OTP 활성 정보가 없어 발생하는 로그인 문제 해결
  src/main/java/page/clab/api/domain/application/domain/Application.java
  src/main/java/page/clab/api/domain/login/application/LoginService.java
Labels: 🐞 Bug

#347 슬랙 메시지 개선 완료
  src/main/java/page/clab/api/domain/login/application/AccountLockInfoService.java
  src/main/java/page/clab/api/domain/login/domain/RedisToken.java
  src/main/java/page/clab/api/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
Labels: 🔨 Refactor

#350 클라이언트 입력값에 대한 처리 개선 완료
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#352 커뮤니티 게시글 상세 조회 반환값 추가 완료
  src/main/java/page/clab/api/domain/board/dto/response/BoardDetailsResponseDto.java
Labels: 🔨 Refactor

#357 커뮤니티 게시글 조회 API 개선 완료
  src/main/java/page/clab/api/domain/board/application/BoardService.java
  src/main/java/page/clab/api/domain/board/dto/response/BoardCategoryResponseDto.java
Labels: 🔨 Refactor
