Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-06, with the labels that each got.

#360 대댓글의 순서가 정렬되지 않는 버그 해결
  src/main/java/page/clab/api/domain/comment/application/CommentService.java
  src/main/java/page/clab/api/domain/comment/domain/Comment.java
Labels: 🐞 Bug

#362 Jenkins 컨테이너에서 발생하는 도커 소켓 연결 문제 수정 완료
  Dockerfile
  deploy/Dockerfile
  deploy/docker-compose.yml
  deploy/entrypoint.sh
Labels: 🐞 Bug, 🌎 Intra

#364 IP 지리적 위치 서비스 개선 완료
  src/main/java/page/clab/api/domain/login/application/LoginAttemptLogService.java
  src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/filter/IPinfoSpringFilter.java
  src/main/java/page/clab/api/global/util/HttpReqResUtil.java
Labels: 🔨 Refactor

#366 젠킨스 개선 완료
  jenkins/Dockerfile
  jenkins/Jenkinsfile
  src/test/java/page/clab/api/ApiApplicationTests.java
Labels: 🔨 Refactor, 🌎 Intra

#367 이미지 파일 업로드 시 회전 버그 해결
  build.gradle
  src/main/java/page/clab/api/global/common/file/application/FileHandler.java
  src/main/java/page/clab/api/global/config/WebConfig.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🐞 Bug

#369 이메일 전송 로직 개선 완료
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
  src/main/java/page/clab/api/global/common/email/domain/EmailTask.java
Labels: 🔨 Refactor

#372 젠킨스 슬랙 알림 개선 완료
  jenkins/Jenkinsfile
Labels: 🔨 Refactor, ✨ Feature

#373 일정 조회가 되지 않는 현상 해결
  src/main/java/page/clab/api/domain/schedule/application/ScheduleService.java
  src/main/java/page/clab/api/domain/schedule/dao/ScheduleRepositoryCustom.java
  src/main/java/page/clab/api/domain/schedule/dao/ScheduleRepositoryImpl.java
Labels: 🔨 Refactor, 🐞 Bug

#376 지원단위별 계정 통합 생성 시 이메일이 보내지지 않는 현상 해결
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
Labels: 🐞 Bug

#378 모니터링 시스템 도입 완료
  .gitignore
  build.gradle
  jenkins/Jenkinsfile
  src/main/java/page/clab/api/global/auth/application/WhitelistService.java
  src/main/java/page/clab/api/global/config/AuthenticationConfig.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/config/WhitelistAccountProperties.java
  src/main/java/page/clab/api/global/config/WhitelistPatternsProperties.java
  src/main/java/page/clab/api/global/util/SwaggerUtil.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature

#379 IpAuthenticationFilter 개선 완료
  src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
Labels: 🔨 Refactor

#380 서버 재배포
  .gitignore
  build.gradle
  jenkins/Jenkinsfile
  src/main/java/page/clab/api/global/auth/application/WhitelistService.java
  src/main/java/page/clab/api/global/auth/filter/IpAuthenticationFilter.java
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
  src/main/java/page/clab/api/global/config/AuthenticationConfig.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/config/WhitelistAccountProperties.java
  src/main/java/page/clab/api/global/config/WhitelistPatternsProperties.java
  src/main/java/page/clab/api/global/util/SwaggerUtil.java
  src/main/resources/logback-spring.xml
Labels: 🔨 Refactor, ✨ Feature, 🐞 Bug

#382 젠킨스 슬랙 메시지 개선 완료
  jenkins/Jenkinsfile
Labels: 🔨 Refactor

#384 젠킨스 웹훅 미작동 오류 수정 완료
  jenkins/Jenkinsfile
Labels: 🐞 Bug

#386 슬랙 알림 로직 분리 및 유동적 알림 설정 가능하도록 변경 완료
  src/main/java/page/clab/api/domain/application/application/ApplicationService.java
  src/main/java/page/clab/api/domain/board/application/BoardService.java
  src/main/java/page/clab/api/domain/board/domain/Board.java
  src/main/java/page/clab/api/global/common/slack/api/NotificationSettingController.java
  src/main/java/page/clab/api/global/common/slack/application/NotificationSettingService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
  src/main/java/page/clab/api/global/common/slack/dao/NotificationSettingRepository.java
  src/main/java/page/clab/api/global/common/slack/domain/AlertType.java
  src/main/java/page/clab/api/global/common/slack/domain/AlertTypeConverter.java
  src/main/java/page/clab/api/global/common/slack/domain/AlertTypeResolver.java
  src/main/java/page/clab/api/global/common/slack/domain/GeneralAlertType.java
  src/main/java/page/clab/api/global/common/slack/domain/NotificationSetting.java
  src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
  src/main/java/page/clab/api/global/common/slack/dto/request/NotificationSettingUpdateRequestDto.java
  src/main/java/page/clab/api/global/common/slack/dto/response/NotificationSettingResponseDto.java
  src/main/java/page/clab/api/global/common/slack/event/NotificationEvent.java
  src/main/java/page/clab/api/global/common/slack/exception/AlertTypeNotFoundException.java
  src/main/java/page/clab/api/global/common/slack/listener/NotificationListener.java
  src/main/resources/messages.properties
Labels: 🔨 Refactor

#389 모집공고 상태 자동변경 로직 작성 완료
  src/main/java/page/clab/api/domain/recruitment/application/RecruitmentService.java
  src/main/java/page/clab/api/domain/recruitment/domain/Recruitment.java
  src/main/java/page/clab/api/domain/recruitment/domain/RecruitmentStatus.java
  src/main/java/page/clab/api/domain/recruitment/dto/request/RecruitmentRequestDto.java
  src/main/java/page/clab/api/domain/recruitment/dto/request/RecruitmentUpdateRequestDto.java
  src/main/java/page/clab/api/domain/recruitment/dto/response/RecruitmentResponseDto.java
  src/main/java/page/clab/api/global/config/TransactionConfig.java
  src/main/resources/messages.properties
Labels: ✨ Feature

#394 모집 공고 상태 응답값 변경 완료
  src/main/java/page/clab/api/domain/recruitment/domain/RecruitmentStatus.java
  src/main/java/page/clab/api/domain/recruitment/dto/response/RecruitmentResponseDto.java
Labels: 🔨 Refactor

#396 게시글에 이모지로 반응하기 기능추가
  build.gradle
  src/main/java/page/clab/api/domain/board/api/BoardController.java
  src/main/java/page/clab/api/domain/board/application/BoardService.java
  src/main/java/page/clab/api/domain/board/dao/BoardEmojiRepository.java
  src/main/java/page/clab/api/domain/board/dao/BoardLikeRepository.java
  src/main/java/page/clab/api/domain/board/domain/Board.java
  src/main/java/page/clab/api/domain/board/domain/BoardEmoji.java
  src/main/java/page/clab/api/domain/board/domain/BoardLike.java
  src/main/java/page/clab/api/domain/board/dto/request/BoardLikeRequestDto.java
  src/main/java/page/clab/api/domain/board/dto/request/BoardRequestDto.java
  src/main/java/page/clab/api/domain/board/dto/response/BoardDetailsResponseDto.java
  src/main/java/page/clab/api/domain/board/dto/response/BoardEmojiCountResponseDto.java
  src/main/java/page/clab/api/domain/comment/application/CommentService.java
  src/main/java/page/clab/api/domain/comment/domain/CommentLike.java
  src/main/java/page/clab/api/domain/comment/dto/request/CommentLikeRequestDto.java
  src/main/java/page/clab/api/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/page/clab/api/global/exception/InvalidEmojiException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/java/page/clab/api/global/util/EmojiUtils.java
Labels: ✨ Feature
