Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-07, with the labels that each got.

#421 의존성 업데이트로 인한 JWT 파싱 오류 수정 완료
  build.gradle
  src/main/java/page/clab/api/global/auth/jwt/JwtTokenProvider.java
Labels: 🐞 Bug

#423 커뮤니티 게시글 작성자가 로그인 된 본인으로 응답되는 버그 해결
  src/main/java/page/clab/api/domain/community/board/application/service/BoardDetailsRetrievalService.java
  src/main/java/page/clab/api/domain/community/board/application/service/BoardRetrievalService.java
  src/main/java/page/clab/api/domain/community/board/application/service/BoardsByCategoryRetrievalService.java
  src/main/java/page/clab/api/domain/community/board/application/service/DeletedBoardsRetrievalService.java
Labels: 🐞 Bug

#430 댓글 조회시 대댓글 개수도 포함되도록 변경 완료
  src/main/java/page/clab/api/domain/community/comment/application/service/CommentRetrievalService.java
  src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
Labels: 🔨 Refactor

#432 Cache-Control 설정을 통한 파일 캐싱 최적화 완료
  src/main/java/page/clab/api/global/config/WebConfig.java
Labels: ✨ Feature

#434 업로드 파일 정보를 가져오지 못하는 오류 수정
  src/main/java/page/clab/api/global/common/file/domain/UploadedFile.java
Labels: 🐞 Bug
