Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-08, with the labels that each got.

#445 채용공고, 뉴스 복원 완료
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/in/web/JobPostingDetailsRetrievalController.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/in/web/JobPostingsByConditionsRetrievalController.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingMapper.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingPersistenceAdapter.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepository.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepositoryCustom.java
  src/main/java/page/clab/api/domain/community/jobPosting/adapter/out/persistence/JobPostingRepositoryImpl.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/dto/response/JobPostingDetailsResponseDto.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/dto/response/JobPostingResponseDto.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/port/in/RetrieveJobPostingDetailsUseCase.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/port/in/RetrieveJobPostingsByConditionsUseCase.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/port/out/RetrieveJobPostingPort.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/service/JobPostingDetailsRetrievalService.java
  src/main/java/page/clab/api/domain/community/jobPosting/application/service/JobPostingsByConditionsRetrievalService.java
  src/main/java/page/clab/api/domain/community/news/adapter/in/web/NewsByConditionsRetrievalController.java
  src/main/java/page/clab/api/domain/community/news/adapter/in/web/NewsDetailsRetrievalController.java
  src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsMapper.java
  src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsPersistenceAdapter.java
  src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepository.java
  src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepositoryCustom.java
  src/main/java/page/clab/api/domain/community/news/adapter/out/persistence/NewsRepositoryImpl.java
  src/main/java/page/clab/api/domain/community/news/application/dto/response/NewsDetailsResponseDto.java
  src/main/java/page/clab/api/domain/community/news/application/dto/response/NewsResponseDto.java
  src/main/java/page/clab/api/domain/community/news/application/port/in/RetrieveNewsByConditionsUseCase.java
  src/main/java/page/clab/api/domain/community/news/application/port/in/RetrieveNewsDetailsUseCase.java
  src/main/java/page/clab/api/domain/community/news/application/port/out/RetrieveNewsPort.java
  src/main/java/page/clab/api/domain/community/news/application/service/NewsByConditionsRetrievalService.java
  src/main/java/page/clab/api/domain/community/news/application/service/NewsDetailsRetrievalService.java
Labels: 🔨 Refactor

#446 오픈소스 프로젝트 전환 완료
  CONTRIBUTING.md
  CONTRIBUTING_EN.md
  README.md
  README_EN.md
  config/default
  deploy/Dockerfile
  deploy/docker-compose.yml
  deploy/entrypoint.sh
  images/Entity-Relationship-Diagram.png
  images/Monitoring-Services-Diagram.png
  images/System-Architecture-Diagram.png
  infra/.env
  infra/docker-compose.yml
  jenkins/Dockerfile
  jenkins/Jenkinsfile
  monitoring/docker-compose.yml
  monitoring/loki/loki-config.yml
  monitoring/prometheus/prometheus.yml
  monitoring/promtail/config.yml
  nginx/default.conf.template
  nginx/nginx.conf
  src/main/resources/application.yml
Labels: 🔨 Refactor, 🌎 Intra

#451 'io.jsonwebtoken ' 0.12.x 업데이트에 따른 JWT 생성 및 파싱 로직 마이그레이션 완료
  src/main/java/page/clab/api/global/auth/jwt/JwtTokenProvider.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#448 활동 그룹 게시판 API 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupBoardController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoard.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardChildResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupProjectResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupStudyResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/AssignmentSubmissionWithFeedbackResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/FeedbackResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/AssignmentBoardHasNoDueDateTimeException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/FeedbackBoardHasNoContentException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#458 회비 정보 조회 시 회비 요청자 정보가 잘못 들어가는 문제 수정 완료
  src/main/java/page/clab/api/domain/members/membershipFee/application/service/MembershipFeesByConditionsRetrievalService.java
Labels: 🐞 Bug

#459 활동 상세 조회 API 응답 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupDetailResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupProjectResponseDto.java
Labels: 🔨 Refactor

#462 회비 정보 수정 권한 ADMIN으로 수정 완료
  src/main/java/page/clab/api/domain/members/membershipFee/adapter/in/web/MembershipFeeUpdateController.java
Labels: 🔨 Refactor

#466 운영진 슬랙 알림 기능 추가 완료
  src/main/java/page/clab/api/domain/community/board/application/service/BoardRegisterService.java
  src/main/java/page/clab/api/domain/members/membershipFee/application/service/MembershipFeeRegisterService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
  src/main/java/page/clab/api/global/common/slack/domain/AlertTypeConverter.java
  src/main/java/page/clab/api/global/common/slack/domain/ExecutivesAlertType.java
  src/main/java/page/clab/api/global/common/slack/domain/GeneralAlertType.java
  src/main/java/page/clab/api/global/common/slack/domain/SlackBoardInfo.java
  src/main/java/page/clab/api/global/common/slack/domain/SlackMembershipFeeInfo.java
  src/main/java/page/clab/api/global/common/slack/event/NotificationEvent.java
  src/main/java/page/clab/api/global/common/slack/listener/NotificationListener.java
  src/main/java/page/clab/api/global/config/SlackConfig.java
Labels: ✨ Feature

#469 `@PreAuthorize`를 통한 API 권한 검사 시 403 상태코드 반환하도록 변경 완료
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#470 feat: 활동 그룹 관련 API 응답 내용 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupBoardController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardReferenceDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupBoardStatusUpdatedResponseDto.java
Labels: 🔨 Refactor

#465 feat: API를 통한 사용자 권한 관리 및 회원 정보 제공 완료
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleInfoRetrievalController.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleManagementController.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryCustom.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/dto/request/ChangeMemberRoleRequest.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/dto/response/MemberRoleInfoResponseDto.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/exception/InvalidRoleChangeException.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/ManageMemberRoleUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/RetrieveMemberRoleInfoUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/out/RetrieveMemberPort.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleInfoRetrievalService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleManagementService.java
  src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
  src/main/java/page/clab/api/domain/memberManagement/member/domain/Role.java
  src/main/java/page/clab/api/global/common/slack/domain/SecurityAlertType.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: ✨ Feature

#473 feat(Slack): 도서 대여 신청 운영진 슬랙 알림 기능 추가 완료
  src/main/java/page/clab/api/domain/library/bookLoanRecord/application/service/BookLoanRequestService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackService.java
  src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
  src/main/java/page/clab/api/global/common/slack/domain/ExecutivesAlertType.java
  src/main/java/page/clab/api/global/common/slack/domain/SlackBookLoanRecordInfo.java
Labels: ✨ Feature

#471 refactor: Jenkins CI/CD Pipeline 개선 완료
  jenkins/Jenkinsfile
  jenkins/config.yml
Labels: 🔨 Refactor

#476 refactor: 모집공고 및 지원 관련 API 수정 및 개선 완료
  src/main/java/page/clab/api/domain/hiring/application/adapter/in/web/ApplicationApprovalController.java
  src/main/java/page/clab/api/domain/hiring/application/adapter/in/web/ApplicationApprovalToggleController.java
  src/main/java/page/clab/api/domain/hiring/application/application/exception/RecruitmentNotActiveException.java
  src/main/java/page/clab/api/domain/hiring/application/application/port/in/ApproveApplicationUseCase.java
  src/main/java/page/clab/api/domain/hiring/application/application/port/in/RejectApplicationUseCase.java
  src/main/java/page/clab/api/domain/hiring/application/application/port/in/ToggleApplicationApprovalUseCase.java
  src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationApplyService.java
  src/main/java/page/clab/api/domain/hiring/application/application/service/ApproveApplicationService.java
  src/main/java/page/clab/api/domain/hiring/application/application/service/RejectApplicationService.java
  src/main/java/page/clab/api/domain/hiring/application/domain/Application.java
  src/main/java/page/clab/api/domain/hiring/recruitment/application/service/RecruitmentStatusUpdater.java
  src/main/java/page/clab/api/domain/hiring/recruitment/domain/Recruitment.java
  src/main/java/page/clab/api/domain/hiring/recruitment/domain/RecruitmentStatus.java
  src/main/java/page/clab/api/external/hiring/application/application/port/ExternalRetrieveRecruitmentUseCase.java
  src/main/java/page/clab/api/external/hiring/application/application/service/ExternalRecruitmentRetrievalService.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#480 feat: 모집 공고 절차 추가 및 관련 API 구현 완료
  src/main/java/page/clab/api/domain/hiring/application/application/dto/response/ApplicationPassResponseDto.java
  src/main/java/page/clab/api/domain/hiring/application/application/exception/RecruitmentEndDateExceededException.java
  src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationPassCheckService.java
  src/main/java/page/clab/api/domain/hiring/recruitment/adapter/in/web/RecentRecruitmentsRetrievalController.java
  src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentPersistenceAdapter.java
  src/main/java/page/clab/api/domain/hiring/recruitment/adapter/out/persistence/RecruitmentRepository.java
  src/main/java/page/clab/api/domain/hiring/recruitment/application/dto/response/RecruitmentEndDateResponseDto.java
  src/main/java/page/clab/api/domain/hiring/recruitment/application/port/in/RetrieveRecentRecruitmentsUseCase.java
  src/main/java/page/clab/api/domain/hiring/recruitment/application/port/out/RetrieveRecruitmentPort.java
  src/main/java/page/clab/api/domain/hiring/recruitment/application/service/RecentRecruitmentsRetrievalService.java
  src/main/java/page/clab/api/domain/hiring/recruitment/domain/Recruitment.java
  src/main/java/page/clab/api/domain/hiring/recruitment/domain/RecruitmentStatus.java
  src/main/java/page/clab/api/global/config/SecurityConstants.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: ✨ Feature

#483 fix: 도서 대출시 도서의 대출자 정보가 승인자로 저장되는 버그 수정 완료
  src/main/java/page/clab/api/domain/library/book/application/service/BookDetailsRetrievalService.java
  src/main/java/page/clab/api/domain/library/book/application/service/BooksByConditionsRetrievalService.java
  src/main/java/page/clab/api/domain/library/bookLoanRecord/application/service/BookLoanApprovalService.java
  src/main/java/page/clab/api/external/library/bookLoanRecord/application/port/ExternalRetrieveBookLoanRecordUseCase.java
Labels: 🐞 Bug

#478 refactor: 코드 취약점 보완 및 리팩토링 작업 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
  src/main/java/page/clab/api/global/common/file/application/FileHandler.java
  src/main/java/page/clab/api/global/common/file/application/FileService.java
  src/main/java/page/clab/api/global/common/file/exception/DirectoryCreationException.java
  src/main/java/page/clab/api/global/common/file/exception/FilePermissionException.java
  src/main/java/page/clab/api/global/common/file/exception/InvalidFileAttributeException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/java/page/clab/api/global/util/EncryptionUtil.java
  src/main/java/page/clab/api/global/util/FileUtil.java
  src/main/java/page/clab/api/global/util/ImageCompressionUtil.java
  src/main/java/page/clab/api/global/util/ImageUtil.java
  src/main/java/page/clab/api/global/util/LogSanitizerUtil.java
  src/main/java/page/clab/api/global/util/TempFileUtil.java
Labels: 🔨 Refactor

#492 fix: 멤버 권한 조회 API의 응답에서 메타데이터가 누락되는 문제 수정 완료
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/in/web/MemberRoleInfoRetrievalController.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberPersistenceAdapter.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/in/RetrieveMemberRoleInfoUseCase.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/port/out/RetrieveMemberPort.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRoleInfoRetrievalService.java
Labels: 🐞 Bug

#506 refactor: QA 피드백에 따른 활동 게시판 로직 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupBoardController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/ActivityGroupBoardRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoardCategory.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/AlreadySubmittedThisWeekAssignmentException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#505 refactor : 활동 도메인에서 발생하는 알림 내용 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
Labels: 🔨 Refactor

#504 feat: 파일 접근 보안 강화 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
  src/main/java/page/clab/api/global/auth/filter/FileAccessControlFilter.java
  src/main/java/page/clab/api/global/auth/util/AuthUtil.java
  src/main/java/page/clab/api/global/common/file/application/FileService.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
Labels: ✨ Feature

#507 refactor: QA 피드백에 따른 활동 그룹 로직 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupMemberController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryCustom.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryImpl.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroup.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupRole.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/GroupMember.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/ActivityGroupStatusResponseDto.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dto/response/LeaderInfo.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/ContentLengthExceededException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/DuplicateRoleException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/InactiveMemberException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/InvalidGithubUrlException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/InvalidRoleException.java
  src/main/java/page/clab/api/domain/activity/activitygroup/exception/MemberNotPartOfActivityException.java
  src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
  src/main/java/page/clab/api/global/common/file/api/FileController.java
  src/main/java/page/clab/api/global/common/file/application/FileService.java
  src/main/java/page/clab/api/global/common/file/exception/AssignmentFileUploadFailException.java
  src/main/java/page/clab/api/global/common/file/exception/InvalidPathVariableException.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/resources/messages.properties
Labels: 🔨 Refactor

#511 refactor: 엔드포인트 URI 로깅에 요청 파라미터 추가 완료
  src/main/java/page/clab/api/global/common/slack/application/SlackServiceHelper.java
  src/main/java/page/clab/api/global/config/SecurityConfig.java
  src/main/java/page/clab/api/global/handler/ApiLoggingInterceptor.java
  src/main/java/page/clab/api/global/handler/GlobalExceptionHandler.java
  src/main/java/page/clab/api/global/util/ApiLogger.java
Labels: 🔨 Refactor

#512 refactor: 활동 그룹 리더가 여러 명이 될 수 있음에 따른 코드 수정 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupBoardService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/domain/ActivityGroupBoard.java
  src/main/java/page/clab/api/domain/activity/review/application/service/ReviewRegisterService.java
  src/main/java/page/clab/api/domain/members/schedule/application/service/ScheduleRegisterService.java
Labels: 🔨 Refactor

#494 refactor: 합격자 계정 생성 로직 리팩토링 완료
  src/main/java/page/clab/api/domain/hiring/application/application/dto/request/ApplicationMemberCreationDto.java
  src/main/java/page/clab/api/domain/hiring/application/application/event/ApplicationEventDispatcher.java
  src/main/java/page/clab/api/domain/hiring/application/application/event/ApplicationEventProcessor.java
  src/main/java/page/clab/api/domain/hiring/application/application/event/ApplicationEventProcessorRegistry.java
  src/main/java/page/clab/api/domain/hiring/application/application/event/ApplicationMemberCreatedEvent.java
  src/main/java/page/clab/api/domain/hiring/application/application/event/PositionCreatedByApplicationEvent.java
  src/main/java/page/clab/api/domain/hiring/application/application/service/ApplicationMemberRegisterService.java
  src/main/java/page/clab/api/domain/hiring/application/domain/Application.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/event/ApplicationMemberCreatedProcessor.java
  src/main/java/page/clab/api/domain/memberManagement/member/domain/Member.java
  src/main/java/page/clab/api/domain/memberManagement/position/application/event/PositionCreatedByApplicationProcessor.java
  src/main/java/page/clab/api/domain/memberManagement/position/application/event/PositionEventProcessor.java
Labels: 🔨 Refactor
