Repository kgu-clab/clab-platforms-server, pull requests merged in 2024-10, with the labels that each got.

#580 refactor: 이메일 템플릿 하드코딩 개선 및 외부 관리로 전환 완료
  src/main/java/page/clab/api/domain/memberManagement/member/application/event/ApplicationMemberCreatedProcessor.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberPasswordManagementService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRegisterService.java
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
  src/main/java/page/clab/api/global/common/email/domain/EmailTemplateType.java
  src/main/java/page/clab/api/global/common/email/dto/request/EmailDto.java
  src/main/java/page/clab/api/global/config/EmailTemplateProperties.java
  src/main/resources/templates/clabEmail.html
Labels: 🔨 Refactor

#578 refactor: 활동 멤버 및 지원서 조회 정렬 로직 변경 완료
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryCustom.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryImpl.java
  src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
  src/main/java/page/clab/api/global/util/PaginationUtils.java
Labels: 🔨 Refactor

#585 refactor: 파일 업로드 취약점 보완 완료
  src/main/java/page/clab/api/global/util/FileUtil.java
Labels: 🔨 Refactor

#583 refactor: 비정상적인 서버 접근 시 슬랙 알림 전송 로직 수정 완료
  src/main/java/page/clab/api/global/auth/filter/InvalidEndpointAccessFilter.java
  src/main/java/page/clab/api/global/util/ApiLogger.java
  src/main/java/page/clab/api/global/util/SecurityPatternChecker.java
Labels: 🔨 Refactor

#588 fix: 외부 공개 프로파일(application.yml)의 이메일 템플릿 설정 누락 수정 완료
  src/main/resources/application.yml
Labels: 🐞 Bug

#586 Changelog
  README.md
  build.gradle
  src/main/java/page/clab/api/domain/activity/activitygroup/api/ActivityGroupAdminController.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupAdminService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/application/ActivityGroupMemberService.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepository.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryCustom.java
  src/main/java/page/clab/api/domain/activity/activitygroup/dao/GroupMemberRepositoryImpl.java
  src/main/java/page/clab/api/domain/memberManagement/member/adapter/out/persistence/MemberRepositoryImpl.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/event/ApplicationMemberCreatedProcessor.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberPasswordManagementService.java
  src/main/java/page/clab/api/domain/memberManagement/member/application/service/MemberRegisterService.java
  src/main/java/page/clab/api/global/auth/filter/InvalidEndpointAccessFilter.java
  src/main/java/page/clab/api/global/common/dto/PagedResponseDto.java
  src/main/java/page/clab/api/global/common/email/application/EmailAsyncService.java
  src/main/java/page/clab/api/global/common/email/application/EmailService.java
  src/main/java/page/clab/api/global/common/email/domain/EmailTemplateType.java
  src/main/java/page/clab/api/global/common/email/dto/request/EmailDto.java
  src/main/java/page/clab/api/global/config/EmailTemplateProperties.java
  src/main/java/page/clab/api/global/util/ApiLogger.java
  src/main/java/page/clab/api/global/util/FileUtil.java
  src/main/java/page/clab/api/global/util/PaginationUtils.java
  src/main/java/page/clab/api/global/util/SecurityPatternChecker.java
  src/main/resources/application.yml
  src/main/resources/templates/clabEmail.html
Labels: 🔨 Refactor, dependencies

#593 refactor: POST 요청 응답 상태코드 변경 (200 → 201) 완료
  src/main/java/page/clab/api/global/filter/PostResponseFilter.java
Labels: 🔨 Refactor
